### ISSUE TITLE
为什么会报这个错误

### ISSUE THREAD

**Issue by didingqd** [beilunyang/moemail#4]
利用Github Actions进行部署的
![image.png](https://img.yd6.us.kg/file/1734850054949_image.png)

**Comment by beilunyang** [comment]
请确认 `CLOUDFLARE_API_TOKEN `设置是否正确，`CLOUDFLARE_API_TOKEN `是否设置了正确权限

**Comment by didingqd** [comment]
具体需要哪些权限？我是直接用的`编辑workers`
