### ISSUE TITLE
找不到secret？

### ISSUE THREAD

**Issue by Fangliding** [beilunyang/moemail#5]
Action部署的 AUTH_SECRET 不知道是啥 稍微看了下似乎是个加密用的密钥 生成了一些密钥填进去 log还是错误
MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
![image](https://github.com/user-attachments/assets/5e8ced1d-ba87-4642-8e4b-16622749564b)

**Comment by Fangliding** [comment]
重新研究了一下 pages里的环境变量似乎要重新action部署一次才会更新
推tag的方法有点笨比 建议换成 `workflow_dispatch` 来手动触发
还有我第一次部署的时候没填对参数 后续更正了 但是action里很多初始化设置都识别的是否是第一次运行 导致有的要初始化的东西没有初始化 后面又手动改条件判断的
建议是改成 workflow_dispatch 触发 给一个选项 是否初始化数据库&worker 再跑

**Comment by Fangliding** [comment]
还有一点小建议 邮箱不能手动释放必须手动删除 设成无限有效期的地址的更是只能去d1手动删 如果能删就好了
自定义后缀好像只是拼起来 如果不想做多email的ui可以考虑留空或者填个预留值的情况下允许自填后缀？
还有允许设置oauth只允许部分用户什么的 有的可能是自用

**Comment by beilunyang** [comment]
> 重新研究了一下 pages里的环境变量似乎要重新action部署一次才会更新 推tag的方法有点笨比 建议换成 `workflow_dispatch` 来手动触发 还有我第一次部署的时候没填对参数 后续更正了 但是action里很多初始化设置都识别的是否是第一次运行 导致有的要初始化的东西没有初始化 后面又手动改条件判断的 建议是改成 workflow_dispatch 触发 给一个选项 是否初始化数据库&worker 再跑

github 

> 重新研究了一下 pages里的环境变量似乎要重新action部署一次才会更新 推tag的方法有点笨比 建议换成 `workflow_dispatch` 来手动触发 还有我第一次部署的时候没填对参数 后续更正了 但是action里很多初始化设置都识别的是否是第一次运行 导致有的要初始化的东西没有初始化 后面又手动改条件判断的 建议是改成 workflow_dispatch 触发 给一个选项 是否初始化数据库&worker 再跑

已更新，支持手动触发action

**Comment by beilunyang** [comment]
> 还有一点小建议 邮箱不能手动释放必须手动删除 设成无限有效期的地址的更是只能去d1手动删 如果能删就好了 自定义后缀好像只是拼起来 如果不想做多email的ui可以考虑留空或者填个预留值的情况下允许自填后缀？ 还有允许设置oauth只允许部分用户什么的 有的可能是自用

感谢建议！合理，我去支持下
